version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000" # Mapping du port pour accéder à l'app
    volumes:
      - .:/app # Synchronisation du code local pour le développement
      - /app/node_modules
    environment:
      - NODE_ENV=production # Ou "development" selon le besoin
    command: npm run start # Commande pour lancer le service

volumes:
  node_modules: